# Generated by Django 4.1.13 on 2024-07-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='name',
            field=models.CharField(default='Unnamed Step', max_length=100),
        ),
    ]
